---
- hosts: all
  remote_user: ubuntu
  gather_facts: no

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson python-jmespath
  roles:
    - common
    - prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - ec2-3-80-147-43.compute-1.amazonaws.com:9100
        labels:
          env: test
